apiVersion: v1
kind: Service
metadata:
  name: backemd-app
  labels:
    app: backend-app
    spec:
      type: LoadBalancer
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: backend-app